---
- name: Request an ACM certificate
  community.aws.acm_certificate:
    state: present
    domain_name: nodeapp.com
    certificate: "{{ lookup('file', 'cert.pem' ) }}"
    private_key: "{{ lookup('file', 'key.pem' ) }}"
    name_tag: aws_cert
  register: acm_cert

- name: Output ACM Certificate ARN
  debug:
    msg: "ACM Certificate ARN: {{ acm_cert.certificate_arn }}"
