---
- name: Request an ACM certificate
  community.aws.acm_certificate:
    state: present
    domain_name: example.com
    validation_method: DNS
  register: certificate_result

- name: Output ACM Certificate ARN
  debug:
    msg: "ACM Certificate ARN: {{ acm_cert.certificate_arn }}"
