---
- name: Create ECS Task Execution Role
  community.aws.iam_role:
    name: ecsTaskExecutionRole
    description: "Role for ECS task execution"
    assume_role_policy_document:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: "sts:AssumeRole"
    state: present
  register: ecs_role

- name: Attach ECS Task Execution Role Policy
  community.aws.iam_policy:
    iam_type: role
    iam_name: ecsTaskExecutionRole
    policy_name: AmazonECSTaskExecutionRolePolicy
    policy_json: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
          }
        ]
      }
    state: present

- name: Debug created ECS role
  debug:
    var: ecs_role
