---
- name: Create an Application Load Balancer (ALB)
  community.aws.elb_application_lb:
    name: node-todo-alb
    subnets:
      - subnet-002a5ce8983d882ce
      - subnet-0627e7ce05ad83519
    security_groups:
      - sg-01fd5ce1808538dcf
      - sg-031a52696e629233e
    state: present
    wait: yes
  register: alb

- name: Create a Target Group
  community.aws.elb_target_group:
    name: node-todo-tg
    protocol: TCP
    port: 80
    vpc_id: vpc-0a45b2ba8534ce6bd
    health_check_protocol: TCP
    health_check_path: /
    target_type: ip
    state: "present"
  register: targetgroup

- name: Create an ELB with an attached Elastic IP address
  community.aws.elb_network_lb:
    name: elb
    subnet_mappings:
      - SubnetId: subnet-002a5ce8983d882ce
    listeners:
      - Protocol: TCP
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupName: node-todo-tg
    state: present