---
- name: Create ECS Task Execution Role
  amazon.aws.iam_role:
    name: ecsTaskExecutionRole
    description: "Role for ECS task execution"
    assume_role_policy_document:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: "sts:AssumeRole"
    state: present
  register: ecs_role

- name: Attach ECS Task Execution Role Policy
  amazon.aws.iam_policy:
    iam_type: role
    name: ecsTaskExecutionRole
    policy_arn: arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
    state: present

- name: Debug created ECS role
  debug:
    var: ecs_role
