---
- name: Install required Ansible collections
  ansible.builtin.command:
    cmd: ansible-galaxy collection install amazon.aws
  register: ansible_collections_result
  changed_when: ansible_collections_result.rc == 0
  failed_when: ansible_collections_result.rc != 0
  ignore_errors: no

- name: Install required Python packages for AWS
  pip:
    name:
      - boto3
      - botocore
    state: present

- name: Install AWS CLI
  ansible.builtin.shell:
    cmd: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
    creates: /usr/local/bin/aws

- name: Ensure AWS credentials are configured
  ansible.builtin.command:
    cmd: aws configure
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
  when: lookup('env', 'AWS_ACCESS_KEY_ID') == '' or lookup('env', 'AWS_SECRET_ACCESS_KEY') == ''

- name: Check if SSH key exists
  stat:
    path: ~/.ssh/node_todo_key
  register: ssh_key_stat

- name: Generate SSH key pair if not present
  ansible.builtin.command:
    cmd: ssh-keygen -t rsa -b 2048 -f ~/.ssh/node_todo_key -N ""
  when: not ssh_key_stat.stat.exists
